inspec/magic-modules

mmv1/products/compute/inspec.yaml, mmv1/templates/inspec/examples/google_compute_region_health_check/google_compute_region_health_check.erb, mmv1/templates/inspec/examples/google_compute_region_health_check/google_compute_region_health_check_attributes.erb, mmv1/templates/inspec/examples/google_compute_region_health_check/google_compute_region_health_checks.erb, mmv1/templates/inspec/examples/google_memcache_instance/google_memcache_instance_attributes.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Signed-off-by: sa-progress <samir.anand@progress.com>
```release-note:REPLACEME
```
=> Health Region Magic Module Changes

mmv1/TUTORIAL.md, mmv1/products/kms/api.yaml, mmv1/templates/inspec/examples/google_kms_location/google_kms_location.erb, mmv1/templates/inspec/examples/google_kms_location/google_kms_location_attributes.erb, mmv1/templates/inspec/examples/google_kms_location/google_kms_locations.erb
Signed-off-by: sa-progress <samir.anand@progress.com>
read me updated + kms location resource added
```release-note:REPLACEME
```
=> RESOURCE-457 magic-module-gcp-cloud-kms-projects-locations

mmv1/TUTORIAL.md, mmv1/products/kms/api.yaml, mmv1/templates/inspec/examples/google_kms_crypto_key_version/google_kms_crypto_key_version.erb, mmv1/templates/inspec/examples/google_kms_crypto_key_version/google_kms_crypto_key_version_attributes.erb, mmv1/templates/inspec/examples/google_kms_crypto_key_version/google_kms_crypto_key_versions.erb
Signed-off-by: sa-progress <samir.anand@progress.com>
```release-note:REPLACEME
```
=> RESOURCE-465 New resource crypto key versions added

README.md, mmv1/products/sql/api.yaml, mmv1/products/sql/inspec.yaml, mmv1/templates/inspec/examples/google_sql_database_instance/google_sql_database_instance.erb
=> CHEF-3565 magic-module-development-for-google-sql-database-instances

mmv1/products/dlp/api.yaml, mmv1/products/dlp/inspec.yaml, mmv1/templates/inspec/examples/google_data_loss_prevention_dlp_job/google_data_loss_prevention_dlp_job.erb, mmv1/templates/inspec/examples/google_data_loss_prevention_dlp_job/google_data_loss_prevention_dlp_job_attributes.erb, mmv1/templates/inspec/examples/google_data_loss_prevention_dlp_job/google_data_loss_prevention_dlp_jobs.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
This Pull Request (PR) aims to perform a proof of concept (POC) for upgrading the Google Cloud Platform (GCP) API from V1 to V2 specifically for the Google Data Loss Prevention (DLP) jobs resource. The primary objective of this PR is to evaluate the feasibility and impact of upgrading to the V2 API.
The PR encompasses the following key tasks:
1. Research and Analysis: Conduct a thorough analysis of the differences between the V1 and V2 APIs for the Google DLP jobs resource. Identify the changes required to align the magic-module with the updated API specifications.
2. Implementation: Implement the necessary code changes and enhancements to the magic-module. Update API endpoints, data structures, and authentication mechanisms to accommodate the V2 API. Ensure backward compatibility with …
=> CHEF-4084 magic-module-development-for-poc-on-upgrading-gcp-api-on-additional-resources

mmv1/products/dlp/api.yaml, mmv1/templates/inspec/examples/google_data_loss_prevention_dlp_job/google_data_loss_prevention_dlp_job.erb, mmv1/templates/inspec/examples/google_data_loss_prevention_dlp_job/google_data_loss_prevention_dlp_jobs.erb
Implement the Magic Module for the DLP Job feature. The objective is to configure the DLP Job , enabling repetitive DLP API calls for improved data loss prevention.
Tasks Accomplished:
Resource Configuration: Develop the Magic Module to easily configure the DLP Job, specifying the necessary parameters for integration with the DLP API.
Terraform Implementation: Adding Terraform to provision the required infrastructure resources.
Test Cases: Create Test cases templates.
Documentation: Create Documentation templates.
By completing these tasks, we will successfully implement the Magic Module Inspec development for DLP Job.
```release-note:REPLACEME
```
=> CHEF-4084 DLP Jobs 

mmv1/products/compute/inspec.yaml, mmv1/templates/inspec/examples/google_compute_image_family_view/google_compute_image_family_view.erb, mmv1/templates/inspec/examples/google_compute_image_family_view/google_compute_image_family_views.erb
Magic Module Development for ImageFamilyView
Tasks
=> CHEF-5883-Magic modules development for ImageFamilyView

mmv1/products/compute/inspec.yaml, mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_group.erb, mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_group_attributes.erb, mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_groups.erb, mmv1/templates/inspec/examples/google_data_loss_prevention_deidentify_template/google_data_loss_prevention_deidentify_template.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Magic Module Development for GlobalNetworkEndpointGroup
Tasks
=> CHEF-5991-MagicModule Development for GlobalNetworkEndpointGroup Resource

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_training_pipeline/google_vertex_ai_training_pipeline.erb, mmv1/templates/inspec/examples/google_vertex_ai_training_pipeline/google_vertex_ai_training_pipeline_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_training_pipeline/google_vertex_ai_training_pipelines.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: TrainingPipeline.
- api.yaml configuration for product vertex_ai and resource TrainingPipeline
=> CHEF-5585-MAGIC-MODULE-vertex_ai-TrainingPipeline - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_nas_job/google_vertex_ai_nas_job.erb, mmv1/templates/inspec/examples/google_vertex_ai_nas_job/google_vertex_ai_nas_job_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_nas_job/google_vertex_ai_nas_jobs.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: NasJob.
- api.yaml configuration for product vertex_ai and resource NasJob
=> CHEF-5573-MAGIC-MODULE-vertex_ai-NasJob - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_endpoint/google_vertex_ai_endpoint.erb, mmv1/templates/inspec/examples/google_vertex_ai_endpoint/google_vertex_ai_endpoint_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_endpoint/google_vertex_ai_endpoints.erb, mmv1/templates/inspec/tests/integration/build/gcp-mm.tf, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Endpoint.
- api.yaml configuration for product vertex_ai and resource Endpoint
=> CHEF-5557-MAGIC-MODULE-vertex_ai-Endpoint - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_pipeline_job/google_vertex_ai_pipeline_job.erb, mmv1/templates/inspec/examples/google_vertex_ai_pipeline_job/google_vertex_ai_pipeline_job_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_pipeline_job/google_vertex_ai_pipeline_jobs.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: PipelineJob.
- api.yaml configuration for product vertex_ai and resource PipelineJob
=> CHEF-5575-MAGIC-MODULE-vertex_ai-PipelineJob - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_tensorboard/google_vertex_ai_tensorboard.erb, mmv1/templates/inspec/examples/google_vertex_ai_tensorboard/google_vertex_ai_tensorboard_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_tensorboard/google_vertex_ai_tensorboards.erb, mmv1/templates/inspec/tests/integration/build/gcp-mm.tf, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Tensorboard.
- api.yaml configuration for product vertex_ai and resource Tensorboard
=> CHEF-5581-MAGIC-MODULE-vertex_ai-Tensorboard - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_featurestore/google_vertex_ai_featurestore.erb, mmv1/templates/inspec/examples/google_vertex_ai_featurestore/google_vertex_ai_featurestore_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_featurestore/google_vertex_ai_featurestores.erb, mmv1/templates/inspec/tests/integration/build/gcp-mm.tf, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Featurestore.
- api.yaml configuration for product vertex_ai and resource Featurestore
=> CHEF-5558-MAGIC-MODULE-vertex_ai-Featurestore - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_index_endpoint/google_vertex_ai_index_endpoint.erb, mmv1/templates/inspec/examples/google_vertex_ai_index_endpoint/google_vertex_ai_index_endpoint_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_index_endpoint/google_vertex_ai_index_endpoints.erb, mmv1/templates/inspec/tests/integration/build/gcp-mm.tf, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: IndexEndpoint.
- api.yaml configuration for product vertex_ai and resource IndexEndpoint
=> CHEF-5562-MAGIC-MODULE-vertex_ai-IndexEndpoint - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_hyperparameter_tuning_job/google_vertex_ai_hyperparameter_tuning_job.erb, mmv1/templates/inspec/examples/google_vertex_ai_hyperparameter_tuning_job/google_vertex_ai_hyperparameter_tuning_job_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_hyperparameter_tuning_job/google_vertex_ai_hyperparameter_tuning_jobs.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: HyperparameterTuningJob.
- api.yaml configuration for product vertex_ai and resource HyperparameterTuningJob
=> CHEF-5561-MAGIC-MODULE-vertex_ai-HyperparameterTuningJob - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_featurestore_entity_type_feature/google_vertex_ai_featurestore_entity_type_feature.erb, mmv1/templates/inspec/examples/google_vertex_ai_featurestore_entity_type_feature/google_vertex_ai_featurestore_entity_type_feature_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_featurestore_entity_type_feature/google_vertex_ai_featurestore_entity_type_features.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Featurestores__entityTypes__feature.
- api.yaml configuration for product vertex_ai and resource Featurestores__entityTypes__feature
=> CHEF-5560-MAGIC-MODULE-vertex_ai-Featurestores__entityTypes__feature - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_model_deployment_monitoring_job/google_vertex_ai_model_deployment_monitoring_job.erb, mmv1/templates/inspec/examples/google_vertex_ai_model_deployment_monitoring_job/google_vertex_ai_model_deployment_monitoring_job_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_model_deployment_monitoring_job/google_vertex_ai_model_deployment_monitoring_jobs.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: ModelDeploymentMonitoringJob.
- api.yaml configuration for product vertex_ai and resource ModelDeploymentMonitoringJob
=> CHEF-5569-MAGIC-MODULE-vertex_ai-ModelDeploymentMonitoringJob - Resource Implementation

mmv1/products/vertexai/api.yaml, mmv1/templates/inspec/examples/google_vertex_ai_metadata_store/google_vertex_ai_metadata_store.erb, mmv1/templates/inspec/examples/google_vertex_ai_metadata_store/google_vertex_ai_metadata_store_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_metadata_store/google_vertex_ai_metadata_stores.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: MetadataStore.
- api.yaml configuration for product vertex_ai and resource MetadataStore
=> CHEF-5564-MAGIC-MODULE-vertex_ai-MetadataStore - Resource Implementation

mmv1/templates/inspec/examples/google_vertex_ai_study/google_vertex_ai_studies.erb, mmv1/templates/inspec/examples/google_vertex_ai_study/google_vertex_ai_study.erb, mmv1/templates/inspec/examples/google_vertex_ai_study/google_vertex_ai_study_attributes.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Study.
- api.yaml configuration for product vertex_ai and resource Study
=> CHEF-5579-MAGIC-MODULE-vertex_ai-Study - Resource Implementation

mmv1/templates/inspec/examples/google_vertex_ai_index/google_vertex_ai_index.erb, mmv1/templates/inspec/examples/google_vertex_ai_index/google_vertex_ai_index_attributes.erb, mmv1/templates/inspec/examples/google_vertex_ai_index/google_vertex_ai_indices.erb, mmv1/templates/inspec/tests/integration/build/gcp-mm.tf, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: vertex_ai and resource: Index.
- api.yaml configuration for product vertex_ai and resource Index
=> CHEF-5563-MAGIC-MODULE-vertex_ai-Index - Resource Implementation

mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
=> Mm-attribute file has grbage values  which is removed.

mmv1/products/composer/api.yaml, mmv1/products/composer/inspec.yaml, mmv1/templates/inspec/examples/google_composer_project_location_image_version/google_composer_project_location_image_version.erb, mmv1/templates/inspec/examples/google_composer_project_location_image_version/google_composer_project_location_image_version_attributes.erb, mmv1/templates/inspec/examples/google_composer_project_location_image_version/google_composer_project_location_image_versions.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: composer and resource: Projects__locations__imageVersion.
- api.yaml configuration for product composer and resource Projects__locations__imageVersion
=> CHEF-7365-MAGIC-MODULE-composer-Projects__locations__imageVersion - Resource Implementation

mmv1/products/compute/api.yaml
=> Service Attachment updated

mmv1/products/compute/inspec.yaml
=> Vpngateways inspec minversion fix

mmv1/products/compute/inspec.yaml
=> Service Attachment inspec minversion fix

mmv1/products/composer/api.yaml
Reverts inspec/magic-modules#148
=> Revert "Composer api yaml update"

mmv1/products/composer/api.yaml, mmv1/templates/inspec/examples/google_composer_project_location_environment/google_composer_project_location_environment.erb, mmv1/templates/inspec/examples/google_composer_project_location_environment/google_composer_project_location_environment_attributes.erb, mmv1/templates/inspec/examples/google_composer_project_location_environment/google_composer_project_location_environments.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: composer and resource: Projects__locations__environment.
- api.yaml configuration for product composer and resource Projects__locations__environment
=> CHEF-7364-MAGIC-MODULE-composer-Projects__locations__environment - Resource Implementation

mmv1/products/servicenetworking/api.yaml, mmv1/products/servicenetworking/inspec.yaml, mmv1/templates/inspec/examples/google_service_networking_service_connection/google_service_networking_service_connection.erb, mmv1/templates/inspec/examples/google_service_networking_service_connection/google_service_networking_service_connection_attributes.erb, mmv1/templates/inspec/examples/google_service_networking_service_connection/google_service_networking_service_connections.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
=> CHEF-7377-MAGIC-MODULE-servicenetworking-Services_connection

mmv1/products/secretmanager/inspec.yaml, mmv1/templates/inspec/examples/google_secret_manager_secret/google_secret_manager_secret.erb, mmv1/templates/inspec/examples/google_secret_manager_secret/google_secret_manager_secret_attributes.erb, mmv1/templates/inspec/examples/google_secret_manager_secret/google_secret_manager_secrets.erb, mmv1/templates/inspec/examples/google_secret_manager_secret_version/google_secret_manager_secret_version.erb, mmv1/templates/inspec/examples/google_secret_manager_secret_version/google_secret_manager_secret_version_attributes.erb, mmv1/templates/inspec/examples/google_secret_manager_secret_version/google_secret_manager_secret_versions.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
=> CHEF-7375-MAGIC-MODULE-secretmanager-Projects_secret

mmv1/products/cloudkms/api.yaml, mmv1/products/cloudkms/inspec.yaml, mmv1/templates/inspec/examples/google_cloudkms_project_location_key_ring/google_cloudkms_project_location_key_ring.erb, mmv1/templates/inspec/examples/google_cloudkms_project_location_key_ring/google_cloudkms_project_location_key_ring_attributes.erb, mmv1/templates/inspec/examples/google_cloudkms_project_location_key_ring/google_cloudkms_project_location_key_rings.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: cloudkms and resource: Projects__locations__keyRing.
- api.yaml configuration for product cloudkms and resource Projects__locations__keyRing
=> CHEF-MAGIC-MODULE-cloudkms-Projects__locations__keyRing - Resource Implementation

mmv1/products/apigee/api.yaml, mmv1/templates/inspec/examples/google_apigee_organization_api_revision/google_apigee_organization_api_revision.erb, mmv1/templates/inspec/examples/google_apigee_organization_api_revision/google_apigee_organization_api_revision_attributes.erb, mmv1/templates/inspec/examples/google_apigee_organization_api_revision/google_apigee_organization_api_revisions.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: apigee and resource: Organizations__apis__revision.
- api.yaml configuration for product apigee and resource Organizations__apis__revision
=> 7361_2-MAGIC-MODULE-apigee-Organizations__apis__revision - Resource Implementation

mmv1/products/compute/inspec.yaml
=> Exclude removed from InSpec yaml

mmv1/products/compute/inspec.yaml
=> Exclude removed for Packet Mirroring

mmv1/products/compute/inspec.yaml
=> Override tags removed

mmv1/products/compute/inspec.yaml
=> Exclude removed

mmv1/products/compute/inspec.yaml
=> Exclude removed for resource policy

mmv1/products/orgpolicy/api.yaml
=> version updated from v1 to v2

mmv1/products/orgpolicy/inspec.yaml
=> Only sinhular resource config

mmv1/products/orgpolicy/api.yaml, mmv1/templates/inspec/examples/google_orgpolicy_organization_constraint/google_orgpolicy_organization_constraint.erb, mmv1/templates/inspec/examples/google_orgpolicy_organization_constraint/google_orgpolicy_organization_constraint_attributes.erb, mmv1/templates/inspec/examples/google_orgpolicy_organization_constraint/google_orgpolicy_organization_constraints.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: orgpolicy_v2 and resource: Organizations__constraint.
- api.yaml configuration for product orgpolicy_v2 and resource Organizations__constraint
=> CHEF-7349_5-MAGIC-MODULE-orgpolicy_v2-Organizations__constraint - Resource Implementation

mmv1/products/orgpolicy/api.yaml, mmv1/templates/inspec/examples/google_orgpolicy_project_constraint/google_orgpolicy_project_constraint.erb, mmv1/templates/inspec/examples/google_orgpolicy_project_constraint/google_orgpolicy_project_constraint_attributes.erb, mmv1/templates/inspec/examples/google_orgpolicy_project_constraint/google_orgpolicy_project_constraints.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: orgpolicy_v2 and resource: Projects__constraint.
- api.yaml configuration for product orgpolicy_v2 and resource Projects__constraint
=> CHEF-7351_1-MAGIC-MODULE-orgpolicy_v2-Projects__constraint - Resource Implementation

mmv1/products/orgpolicy/inspec.yaml
=> Plural only

mmv1/products/orgpolicy/api.yaml
Automatically generated by magic modules for service: orgpolicy_v2 and resource: Organizations__constraint.
- api.yaml configuration for product orgpolicy_v2 and resource Organizations__constraint
=> CHEF-7349-v4-MAGIC-MODULE-orgpolicy_v2-Organizations__constraint - Resource Implementation

mmv1/products/compute/inspec.yaml, mmv1/products/metastore/inspec.yaml
=> Docs updated

mmv1/products/metastore/api.yaml, mmv1/templates/inspec/examples/google_metastore_project_location_federation/google_metastore_project_location_federation.erb, mmv1/templates/inspec/examples/google_metastore_project_location_federation/google_metastore_project_location_federation_attributes.erb, mmv1/templates/inspec/examples/google_metastore_project_location_federation/google_metastore_project_location_federations.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
=> CHEF-12255 Dataproc Metastroe resource configuration

mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service/google_dataproc_metastore_project_location_service.erb, mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service/google_dataproc_metastore_project_location_service_attributes.erb, mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service/google_dataproc_metastore_project_location_services.erb
=> Meta store resource name updated with dataproc prefix.

mmv1/products/bigtableadmin/api.yaml, mmv1/products/bigtableadmin/inspec.yaml, mmv1/templates/inspec/examples/google_bigtableadmin_project_instance_cluster/google_bigtableadmin_project_instance_cluster.erb, mmv1/templates/inspec/examples/google_bigtableadmin_project_instance_cluster/google_bigtableadmin_project_instance_cluster_attributes.erb, mmv1/templates/inspec/examples/google_bigtableadmin_project_instance_cluster/google_bigtableadmin_project_instance_clusters.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: bigtableadmin_v2 and resource: Projects__instances__cluster.
- api.yaml configuration for product bigtableadmin_v2 and resource Projects__instances__cluster
=> CHEF-12475-v2-MAGIC-MODULE-bigtableadmin_v2-Projects__instances__cluster - Resource Implementation

mmv1/products/compute/api.yaml, mmv1/templates/inspec/examples/google_compute_region_security_policy/google_compute_region_security_policies.erb, mmv1/templates/inspec/examples/google_compute_region_security_policy/google_compute_region_security_policy.erb
Automatically generated by magic modules for service: compute_v1 and resource: RegionSecurityPolicy.
- api.yaml configuration for product compute_v1 and resource RegionSecurityPolicy
=> CHEF-7186-MAGIC-MODULE-compute_v1-RegionSecurityPolicy - Resource Implementation

mmv1/products/run/api.yaml
Automatically generated by magic modules for service: run_v2 and resource: Service.
- api.yaml configuration for product run_v2 and resource Service
=> CHEF-12482-v1.4-MAGIC-MODULE-run_v2-Service - Resource Implementation

mmv1/products/datafusion/api.yaml
Automatically generated by magic modules for service: datafusion_v1 and resource: Instance.
- api.yaml configuration for product datafusion_v1 and resource Instance
=> CHEF-12253-v4-MAGIC-MODULE-datafusion_v1-Instance - Resource Implementation

mmv1/products/apigee/api.yaml, mmv1/templates/inspec/examples/google_apigee_organization_instance_attachment/google_apigee_organization_instance_attachment.erb, mmv1/templates/inspec/examples/google_apigee_organization_instance_attachment/google_apigee_organization_instance_attachment_attributes.erb, mmv1/templates/inspec/examples/google_apigee_organization_instance_attachment/google_apigee_organization_instance_attachments.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: apigee_v1 and resource: Organizations__instances__attachment.
- api.yaml configuration for product apigee_v1 and resource Organizations__instances__attachment
=> CHEF-12251-v2-MAGIC-MODULE-apigee_v1-Organizations__instances__attachment - Resource Implementation

mmv1/products/bigtableadmin/api.yaml
=> Removed untagged description

mmv1/products/dataproc/api.yaml, mmv1/templates/inspec/examples/google_dataproc_batch/google_dataproc_batch.erb, mmv1/templates/inspec/examples/google_dataproc_batch/google_dataproc_batch_attributes.erb, mmv1/templates/inspec/examples/google_dataproc_batch/google_dataproc_batches.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: dataproc_v1 and resource: Batch.
- api.yaml configuration for product dataproc_v1 and resource Batch
=> CHEF-12247-V0-MAGIC-MODULE-dataproc_v1-Batch - Resource Implementation

mmv1/products/monitoring/inspec.yaml
=> Legacy name Removed

mmv1/products/monitoring/api.yaml, mmv1/templates/inspec/examples/google_monitoring_project_group/google_monitoring_project_group.erb, mmv1/templates/inspec/examples/google_monitoring_project_group/google_monitoring_project_group_attributes.erb, mmv1/templates/inspec/examples/google_monitoring_project_group/google_monitoring_project_groups.erb, mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml
Automatically generated by magic modules for service: monitoring_v3 and resource: Projects__group.
- api.yaml configuration for product monitoring_v3 and resource Projects__group
=> CHEF-12238-V2-MAGIC-MODULE-monitoring_v3-Projects__group - Resource Implementation
