inspec/magic-modules

mmv1/products/cloudscheduler/api.yaml
mmv1/products/cloudscheduler/terraform.yaml
mmv1/templates/terraform/custom_flatten/cloud_scheduler_paused.go.erb
mmv1/templates/terraform/encoders/cloud_scheduler.go.erb
mmv1/templates/terraform/examples/scheduler_job_paused.tf.erb
mmv1/templates/terraform/post_create/cloud_scheduler.go.erb
mmv1/templates/terraform/post_update/cloud_scheduler.go.erb
mmv1/templates/terraform/update_encoder/cloud_scheduler.go.erb
mmv1/third_party/terraform/tests/resource_cloud_scheduler_job_test.go

Closes inspec/inspec-gcp#430
Cherry-picked from GoogleCloudPlatform/magic-modules#6304
* Add `state` field to `google_cloud_scheduler_job` as output
* Add `paused` field to `google_cloud_scheduler_job` to control state
* Add example of paused `google_cloud_scheduler_job`
* Add handwritten test for paused `google_cloud_scheduler_job`
* Make `paused` argument default to value derived from API via custom flatten function
```release-note:REPLACEME
```

Add `paused` attribute to `google_cloud_scheduler_job` resource (#6304)

---

mmv1/templates/inspec/examples/google_data_loss_prevention_job_trigger/google_data_loss_prevention_job_trigger.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_job_trigger/google_data_loss_prevention_job_trigger_attributes.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_job_trigger/google_data_loss_prevention_job_triggers.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

This pull request addresses the task of implementing the Magic Module for the DLP Job Trigger feature, which aims to enhance data loss prevention capabilities through repetitive DLP API calls. 
Tasks Completed:
- Resource Configuration
- Terraform Implementation: We have incorporated Terraform to provision the essential infrastructure resources required for the DLP Job Trigger feature. This addition ensures that the necessary resources are set up correctly and consistently.
- Test Cases: Test case templates have been created to thoroughly validate the functionality of the implemented Magic Module. These test cases will be instrumental in ensuring the reliability and correctness of the DLP Job Trigger feature.
- Documentation: To provide comprehensive guidance to users, documentation …

CHEF-4081 DLP Trigger jobs inspec api.yaml + terrform implementation

---

mmv1/templates/inspec/examples/google_data_loss_prevention_inspect_template/google_data_loss_prevention_inspect_template.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_inspect_template/google_data_loss_prevention_inspect_template_attributes.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_inspect_template/google_data_loss_prevention_inspect_templates.erb

Description
Implement the Magic Module for the DLP InspectTemplate feature. The objective is to configure the DLP InspectTemplate, enabling repetitive DLP API calls for improved data loss prevention.
Tasks:
Resource Configuration: Develop the Magic Module to easily configure the DLP InspectTemplate, specifying the necessary parameters for integration with the DLP API.
Terraform Implementation: Adding Terraform to provision the required infrastructure resources.
Test Cases: Create Test cases templates.
Documentation: Create Documentation templates.
By completing these tasks, we will successfully implement the Magic Module Inspec development for DLP InspectTemplate. …

CHEF-4082 DLP InspectTemplate Resource Magic Module Development

---

mmv1/products/dlp/api.yaml
mmv1/templates/inspec/examples/google_data_loss_prevention_stored_info_type/google_data_loss_prevention_stored_info_type.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_stored_info_type/google_data_loss_prevention_stored_info_type_attributes.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_stored_info_type/google_data_loss_prevention_stored_info_types.erb

Implement the Magic Module for the DLP StoredInfoType feature. The objective is to configure the DLP StoredInfoType, enabling repetitive DLP API calls for improved data loss prevention.
Tasks:
Resource Configuration: Develop the Magic Module to easily configure the DLP StoredInfoType, specifying the necessary parameters for integration with the DLP API.
Terraform Implementation: Adding Terraform to provision the required infrastructure resources.
Test Cases: Create Test cases templates.
Documentation: Create Documentation templates.
By completing these tasks, we will successfully implement the Magic Module Inspec development for DLP StoredInfoType. …

CHEF-4085 dlp stored info type resource magic module development

---

mmv1/templates/inspec/examples/google_data_loss_prevention_deidentify_template/google_data_loss_prevention_deidentify_template.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_deidentify_template/google_data_loss_prevention_deidentify_template_attributes.erb
mmv1/templates/inspec/examples/google_data_loss_prevention_deidentify_template/google_data_loss_prevention_deidentify_templates.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Magic Module development for for DLP DeIdentify Templates feature.
Tasks Completed:
Test Case Templates: Test case templates have been created to validate the functionality of the implemented Magic  Module. These test cases will be instrumental in ensuring the reliability and correctness of the DLP DeIdentify Template.
Attribute Changes: Added attribute changes required for Test case template
```release-note:REPLACEME
```

DLP DeIdentify Templates Magic Module Development

---

mmv1/products/vertex_ai
mmv1/products/vertexai/api.yaml
mmv1/products/vertexai/inspec.yaml
mmv1/templates/inspec/examples/google_vertex_ai_dataset/google_vertex_ai_dataset.erb
mmv1/templates/inspec/examples/google_vertex_ai_dataset/google_vertex_ai_dataset_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_dataset/google_vertex_ai_datasets.erb
mmv1/templates/inspec/tests/integration/build/gcp-mm.tf

Automatically generated by magic modules for service: vertex_ai and resource: Dataset.
- api.yaml configuration for product vertex_ai and resource Dataset

CHEF-MAGIC-MODULE-vertex_ai-Dataset - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_dataset/google_vertex_ai_dataset.erb
mmv1/templates/inspec/examples/google_vertex_ai_dataset/google_vertex_ai_datasets.erb
mmv1/templates/inspec/tests/integration/build/gcp-mm.tf

Automatically generated by magic modules for service: vertex_ai and resource: Dataset.
- api.yaml configuration for product vertex_ai and resource Dataset

CHEF-6199-MAGIC-MODULE-vertex_ai-Dataset - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_tensorboard_experiment_run/google_vertex_ai_tensorboard_experiment_run.erb
mmv1/templates/inspec/examples/google_vertex_ai_tensorboard_experiment_run/google_vertex_ai_tensorboard_experiment_run_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_tensorboard_experiment_run/google_vertex_ai_tensorboard_experiment_runs.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: Tensorboards__experiments__run.
- api.yaml configuration for product vertex_ai and resource Tensorboards__experiments__run

CHEF-5583-MAGIC-MODULE-vertex_ai-Tensorboards__experiments__run - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_tensorboards_experiment/google_vertex_ai_tensorboards_experiment.erb
mmv1/templates/inspec/examples/google_vertex_ai_tensorboards_experiment/google_vertex_ai_tensorboards_experiment_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_tensorboards_experiment/google_vertex_ai_tensorboards_experiments.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: Tensorboards__experiment.
- api.yaml configuration for product vertex_ai and resource Tensorboards__experiment

CHEF-5582-MAGIC-MODULE-vertex_ai-Tensorboards__experiment - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_metadata_schema/google_vertex_ai_metadata_stores_metadata_schema.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_metadata_schema/google_vertex_ai_metadata_stores_metadata_schema_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_metadata_schema/google_vertex_ai_metadata_stores_metadata_schemas.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: MetadataStores__metadataSchema.
- api.yaml configuration for product vertex_ai and resource MetadataStores__metadataSchema

CHEF-5568-MAGIC-MODULE-vertex_ai-MetadataStores__metadataSchema - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_context/google_vertex_ai_metadata_stores_context.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_context/google_vertex_ai_metadata_stores_context_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_context/google_vertex_ai_metadata_stores_contexts.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: MetadataStores__context.
- api.yaml configuration for product vertex_ai and resource MetadataStores__context

CHEF-5566-MAGIC-MODULE-vertex_ai-MetadataStores__context - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_artifact/google_vertex_ai_metadata_stores_artifact.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_artifact/google_vertex_ai_metadata_stores_artifact_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_metadata_stores_artifact/google_vertex_ai_metadata_stores_artifacts.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: MetadataStores__artifact.
- api.yaml configuration for product vertex_ai and resource MetadataStores__artifact

CHEF-5565-MAGIC-MODULE-vertex_ai-MetadataStores__artifact - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/products/vertexai/inspec.yaml
mmv1/templates/inspec/examples/google_vertex_ai_datasets_annotation_spec/google_vertex_ai_datasets_annotation_spec.erb
mmv1/templates/inspec/examples/google_vertex_ai_datasets_annotation_spec/google_vertex_ai_datasets_annotation_spec_attributes.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: Datasets__annotationSpec.
- api.yaml configuration for product vertex_ai and resource Datasets__annotationSpec

CHEF-5553-MAGIC-MODULE-vertex_ai-Datasets__annotationSpec - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_nas_jobs_nas_trial_detail/google_vertex_ai_nas_jobs_nas_trial_detail.erb
mmv1/templates/inspec/examples/google_vertex_ai_nas_jobs_nas_trial_detail/google_vertex_ai_nas_jobs_nas_trial_detail_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_nas_jobs_nas_trial_detail/google_vertex_ai_nas_jobs_nas_trial_details.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: NasJobs__nasTrialDetail.
- api.yaml configuration for product vertex_ai and resource NasJobs__nasTrialDetail

CHEF-5574-MAGIC-MODULE-vertex_ai-NasJobs__nasTrialDetail - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_model_evaluation_slice/google_vertex_ai_model_evaluation_slice.erb
mmv1/templates/inspec/examples/google_vertex_ai_model_evaluation_slice/google_vertex_ai_model_evaluation_slice_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_model_evaluation_slice/google_vertex_ai_model_evaluation_slices.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: Models__evaluations__slice.
- api.yaml configuration for product vertex_ai and resource Models__evaluations__slice

CHEF-5572-MAGIC-MODULE-vertex_ai-Models__evaluations__slice - Resource Implementation

---

mmv1/products/vertexai/api.yaml
mmv1/templates/inspec/examples/google_vertex_ai_datasets_data_item/google_vertex_ai_datasets_data_item.erb
mmv1/templates/inspec/examples/google_vertex_ai_datasets_data_item/google_vertex_ai_datasets_data_item_attributes.erb
mmv1/templates/inspec/examples/google_vertex_ai_datasets_data_item/google_vertex_ai_datasets_data_items.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: vertex_ai and resource: Datasets__dataItem.
- api.yaml configuration for product vertex_ai and resource Datasets__dataItem

CHEF-5554-MAGIC-MODULE-vertex_ai-Datasets__dataItem - Resource Implementation

---

mmv1/products/iam/api.yaml
mmv1/templates/inspec/examples/google_iam_project_service_account_key/google_iam_project_service_account_key.erb
mmv1/templates/inspec/examples/google_iam_project_service_account_key/google_iam_project_service_account_key_attributes.erb
mmv1/templates/inspec/examples/google_iam_project_service_account_key/google_iam_project_service_account_keys.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: iam and resource: Projects__serviceAccounts__key.
- api.yaml configuration for product iam and resource Projects__serviceAccounts__key

None-MAGIC-MODULE-iam-Projects__serviceAccounts__key - Resource Implementation

---

mmv1/products/orgpolicy/api.yaml
mmv1/products/orgpolicy/inspec.yaml
mmv1/templates/inspec/examples/google_orgpolicy_folder_policy/google_orgpolicy_folder_policies.erb
mmv1/templates/inspec/examples/google_orgpolicy_folder_policy/google_orgpolicy_folder_policy.erb
mmv1/templates/inspec/examples/google_orgpolicy_folder_policy/google_orgpolicy_folder_policy_attributes.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Automatically generated by magic modules for service: orgpolicy and resource: Folders__policy.
- api.yaml configuration for product orgpolicy and resource Folders__policy

CHEF-ORG-MAGIC-MODULE-orgpolicy-Folders__policy - Resource Implementation

---

mmv1/products/compute/api.yaml
mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_group.erb
mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_group_attributes.erb
mmv1/templates/inspec/examples/google_compute_global_network_endpoint_group/google_compute_global_network_endpoint_groups.erb

Automatically generated by magic modules for service: compute_v1 and resource: GlobalNetworkEndpointGroup.
- api.yaml configuration for product compute_v1 and resource GlobalNetworkEndpointGroup

CHEF-7342_2-MAGIC-MODULE-compute_v1-GlobalNetworkEndpointGroup - Resource Implementation

---

mmv1/api/resource.rb
mmv1/templates/inspec/doc_template.md.erb

CHEF-5596 Magic Module docs update

---

mmv1/products/metastore/api.yaml
mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service_backup/google_dataproc_metastore_project_location_service_backup.erb
mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service_backup/google_dataproc_metastore_project_location_service_backup_attributes.erb
mmv1/templates/inspec/examples/google_dataproc_metastore_project_location_service_backup/google_dataproc_metastore_project_location_service_backups.erb
mmv1/templates/inspec/tests/integration/configuration/mm-attributes.yml

Dataproc prefix added for metastore resource

---

mmv1/products/metastore/api.yaml

Automatically generated by magic modules for service: metastore_v1 and resource: Projects__locations__services__backup.
- api.yaml configuration for product metastore_v1 and resource Projects__locations__services__backup

CHEF-12151-MAGIC-MODULE-metastore_v1-Projects__locations__services__backup - Resource Implementation
